language: python
python:
  - "2.7"
# command to install dependencies
install: "pip install -r requirements.txt --use-mirrors"
# command to run pep8
before_script:  python setup.py pep8
# command to run tests
script: nosetests
